### ISSUE TITLE
li.is-outlined doesn't work

### ISSUE THREAD

**Issue by Lesterdor** [chrisrhymes/bulma-block-list#4]
Hey
I use your Bulma extension with great pleasure. However, I noticed an error that I would like to share with you:

`li.is-outlined `

does not work. The misconduct is already clear directly on your demo page, which is why I refer you there at this point:
[List Item Overrides - example li.is-primary.is-outlined](https://www.csrhymes.com/bulma-block-list/)

As you can see the list item isn't outlined.

Thank you in advance.

**Comment by chrisrhymes** [comment]
Hi @Lesterdor Thanks for the feedback and the bug report. I have released 0.4.1 which should resolve this issue.

**Comment by Lesterdor** [comment]
Hey @chrisrhymes thank you very much for your help! Great work so far!
