### ISSUE TITLE
.is-outlined without specifying color

### ISSUE THREAD

**Issue by janosrusiczki** [chrisrhymes/bulma-block-list#6]
I noticed .is-outlined doesn't work if I don't specify a color.

Is it possible to have an .is-outlined list item without specifying the color (eg. .is-primary, .is-dark)?

**Comment by chrisrhymes** [comment]
Hi @janosrusiczki, thanks for raising this. What would the default colour be for the outline? Would you want it to be grey like the default background colour?

**Comment by janosrusiczki** [comment]
First of all thanks for addressing this issue on a Sunday. :smile:

Yes, I was thinking about the same outline as a simple button, eg: `<button class="button">Button</button>`

**Comment by chrisrhymes** [comment]
This has been added in v0.4.2. Thanks

**Comment by janosrusiczki** [comment]
Many thanks!
